# Generated by Django 2.0.5 on 2018-06-04 13:50

import bridge_lti.utils
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_lti', '0002_auto_20180316_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridgeuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='bridgeuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='ltiprovider',
            name='consumer_key',
            field=models.CharField(db_index=True, default=bridge_lti.utils.short_token, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='ltiprovider',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Consumer key expiration date'),
        ),
        migrations.AlterField(
            model_name='ltiuser',
            name='user_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
